Develop
AlSl94/java-explore-with-me pull request #1
Opened 2022-11-13 20:47 UTC by AlSl94

Docker, Maven, schema.sql

2022-11-29 04:26 UTC, krylov-sergey-sergeevich requested changes
Привет, отличная работа, давай обсудим что можно улучшить

1) Логи должны быть везде в контроллерах это в реальных проектах позволяет отследить "точку входа"
2) Почитать про свагер, это не обязательно но в будущем будет очень кстати
3) Почитать про мапстракт это не обязательно и не надо сейчас применять на будущее
4) Если присмотреться то многие броски исключений очень похожи по тексту и смыслу, давай создадим наследников для базовых исключений например NotFound и будем бросать кастомные например UserNotFound(userId) а тест уже там сам подставляться должен будет
5) Необязательно но полезно: Улучшить readme + добавить схему

2022-11-29 04:26 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/java/ru/practicum/ewm/category/CategoryMapper.java
> +public class CategoryMapper {
Рекомендую почитать на будущее про Mapstruct, сейчас тут его применять излишне

2022-11-29 04:26 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/java/ru/practicum/ewm/category/CategoryService.java
> +public class CategoryService {
Давай избавимся от дублей кода вынеся в вспомогательные методы + подход "сохранить" и если не выйдет выкинуть исключение выглядит не очень хорошо

2022-11-29 04:26 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/java/ru/practicum/ewm/error/ErrorState.java
> +public enum ErrorState {
Хорошая практика

2022-11-29 04:26 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/java/ru/practicum/ewm/error/ExceptionResponse.java
> +public class ExceptionResponse {
Модификаторы доступа давай добавим?

2022-11-29 04:26 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/java/ru/practicum/ewm/event/EventService.java
> +    public List<EventShortDto> initiatorEvents(Long userId, int from, int size) {
название так себе

2022-11-29 04:26 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/java/ru/practicum/ewm/utility/FromSizeRequest.java
> +public class FromSizeRequest extends PageRequest {
Хорошая штука

2022-11-29 04:26 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users
Везде размер varchar 255 это конечно работает - но лучше учитывать специфику поля и делать соответствующие размеры

2022-11-29 04:26 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users
И delete cascade везде указаны? Есть ощущение что еще надо, НО могу ошибаться тут надо аккуратно расставлять

2022-12-01 17:45 UTC, AlSl94 commented on ewm-service/src/main/java/ru/practicum/ewm/category/CategoryMapper.java
> +public class CategoryMapper {
Спасибо большое, посмотрел что это - обязательно почитаю поподробнее. Очень интересно

2022-12-01 17:51 UTC, AlSl94 commented on ewm-service/src/main/java/ru/practicum/ewm/error/ErrorState.java
> +public enum ErrorState {
Спасибо, если честно подсмотрел у товарища, но очень понравилось решение

2022-12-01 17:52 UTC, AlSl94 commented on ewm-service/src/main/java/ru/practicum/ewm/event/EventService.java
> +    public List<EventShortDto> initiatorEvents(Long userId, int from, int size) {
Переделал

2022-12-01 17:53 UTC, AlSl94 commented on ewm-service/src/main/java/ru/practicum/ewm/utility/FromSizeRequest.java
> +public class FromSizeRequest extends PageRequest {
Спасибо Сергею Савельеву за это

2022-12-01 17:55 UTC, AlSl94 commented on ewm-service/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users
Delete cascade такая опасная вещь, что я боюсь с ней играть, в том плане, что если мы сделаем delete cascade, то случайной командой можно удалить всю цепочку таблиц. Поэтому к этому крайне аккуратно подхожу. Если необходимо, я пропишу везде, но вроде как в главных таблицах events, users и тд прописано

2022-12-01 17:55 UTC, AlSl94 commented on ewm-service/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users
Варчары переписал, должно быть получше

2022-12-01 17:56 UTC, AlSl94 commented on ewm-service/src/main/java/ru/practicum/ewm/error/ExceptionResponse.java
> +public class ExceptionResponse {
Проглядел.. Стараюсь не пропускать private поля, но тут видимо взгляд замылился. Спасибо, исправлено!

2022-12-02 19:07 UTC, AlSl94 commented on ewm-service/src/main/java/ru/practicum/ewm/category/CategoryService.java
> +public class CategoryService {
Признаюсь, я не очень понял это замечание. Поэтому не стал лезть :(

2022-12-02 19:43 UTC, AlSl94 commented
Признаюсь честно, не все замечания успел учесть. Т.к. работа совсем не позволила сосредоточиться нормально на дипломном проекте. А еще я оказывается отправил костыль, вместо рабочей версии (без gateway, который соединяет ewm-service и stat-server). В итоге чинил его 2 полных вечера. Бесконечная потеря времени.
В общем, по-итогу отправляю проект таким, надеюсь, что он достаточно приемлем.
П.с. спасибо за ревью, штуки, которые ты рекомендовал к просмотру действительно очень интересные. Надо найти немного освободиться по времени и плотно их просмотреть

2022-12-03 10:33 UTC, krylov-sergey-sergeevich requested changes
**Привет**, работа хорошо поправлена, но я тут начал с других ребят требовать некоторые пункты и будет неправильно если у тебя их не будет, плюс полезно это знать , так что давай последний рывок сделаем и будет зачет:

**Обязательно:**
- readme
-  В некоторых местах можно получше попытаться подумать и избежать дублирования кода, для нахождения таких мест рекомендую самому смотреть pr сверху вниз, а не через IDEA
- **Учесть и поправить нейминг методов:** get - это или получение объекта или исключение, find - это или объект или null

**Не обязательно:**
- @JsonFormat - не везде где можно применен к датам
- Подход с исключениями хорош, но можно лучше. Исключения если присмотреться похожи по структуре, не хочется ли создать структуру исключений или побольше кастомных исключений и не писать каждый раз весь текст причины исключения, а чисто название например NotFoundCategoryException extend NotFoundException это не обязательно, но как на подумать.

p.s если отправишь сегодня до 22-23.00 то проверю сегодня

2022-12-03 10:33 UTC, krylov-sergey-sergeevich commented on ewm-service/pom.xml
> +            <version>4.5.13</version>
Версию вынести в проперти блок pom.xml

2022-12-03 10:33 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/java/ru/practicum/ewm/error/ErrorHandler.java
> +public class ErrorHandler {
Попробуй поизучать как можно сделать так чтобы еще возвращать в сообщение с ошибкой request path по которому был сделан запрос. Один из вариантов это воспользоваться: **HttpServletRequest**

2022-12-03 10:33 UTC, krylov-sergey-sergeevich commented on README.md
> +# _Backend Service For Explore with me application_
ReadMe давай еще лучше: **"Добавим блоки"**

1) Используемые технологии
2) Краткое описание сервисов
3) Команды описаны для старта докера

2022-12-03 10:33 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/java/ru/practicum/ewm/compilation/model/Compilation.java
> +    @ManyToMany(cascade = CascadeType.ALL)
На будущее cascade = CascadeType.ALL - очень опасная штука, но для учебного проекта сойдет

2022-12-03 10:33 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/java/ru/practicum/ewm/event/EventMapper.java
> +    private EventMapper() {
@UtilityClass

2022-12-03 10:33 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/java/ru/practicum/ewm/user/UserMapper.java
> +    private UserMapper() {
Аннотация утилитного класса

2022-12-03 10:33 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS requests
Тут в этой таблице не должно быть DELETE CASCADE?

2022-12-03 15:15 UTC, AlSl94 commented on ewm-service/src/main/java/ru/practicum/ewm/compilation/model/Compilation.java
> +    @ManyToMany(cascade = CascadeType.ALL)
Понял-принял. Запомнил. Спасибо

2022-12-03 15:37 UTC, AlSl94 commented on ewm-service/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS requests
Должно быть :(
Мыльный взгляд™

2022-12-03 15:39 UTC, AlSl94 commented on ewm-service/src/main/java/ru/practicum/ewm/event/EventMapper.java
> +    private EventMapper() {
Прятал UtilityClass за приватным конструктором. Клевая аннотация. Спасибо

2022-12-03 15:41 UTC, AlSl94 commented on ewm-service/src/main/java/ru/practicum/ewm/user/UserMapper.java
> +    private UserMapper() {
Done

2022-12-03 16:00 UTC, AlSl94 commented on ewm-service/src/main/java/ru/practicum/ewm/error/ErrorHandler.java
> +public class ErrorHandler {
Вроде получилось. Совсем несложно, но полезно

2022-12-03 17:14 UTC, AlSl94 commented on README.md
> +# _Backend Service For Explore with me application_
Оформил получше, по-крайней мере стало смотреться более целостно

2022-12-03 17:35 UTC, AlSl94 commented on ewm-service/pom.xml
> +            <version>4.5.13</version>
Никогда так не делал. Удобно..

2022-12-03 18:58 UTC, AlSl94 commented
Не успел сделать правки по всем твоим замечаниям. Очень хотел залететь в окно до 10 часов, чтобы ты проверил работу.
Главное из того, что не сделал - сократил код только в одном месте, хотя вижу еще парочку, где это можно сделать. 
Не сделал исключения по типу EventNotFoundException, т.к. опять же не хватило времени, хотя, если честно, я пытался сделать, но у меня посыпались ошибки, так что я не стал лезть в дебри и оставил, как есть. Но идея мне понравилась, в будущем обязательно зарефакторю код таким образом.

2022-12-04 17:46 UTC, krylov-sergey-sergeevich approved these changes
Привет!

Вот теперь работа отличная, видно что вы овладели языком Java и сопуствующими технологиями. Поэтому зачет и удачи в дальнейшем обучение =)

2022-12-04 19:51 UTC, merged